# .github/workflows/backend.yml
name: Backend CI
on: [push, pull_request]

jobs:
  use-backend-ci:
    uses: GC69720/social_ci-cd/.github/workflows/backend-ci.yml@main
    with:
      image-tag: ${{ github.sha }}
      image-name: ghcr.io/${{ toLower(github.repository_owner) }}/social-backend
      push-image: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
