---
name: ci

'on':
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  app-ci:
    uses: GC69720/social_ci-cd/.github/workflows/python-django.yml@v1
    with:
      python_version: "3.12"
      working_directory: "backend"
      run_tests: true
      upload_test_artifacts: true
      django_settings_module: "app.settings"    # ajuste au nom de ton module settings
      enable_codeql: true
      docker_image_name: ""                     # build image via Podman/Buildah (job suivant)
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: appdb
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U app -d appdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    env:
      DATABASE_URL: "postgres://app:app@localhost:5432/appdb"

  build-image:
    needs: [app-ci]
    uses: GC69720/social_ci-cd/.github/workflows/container-buildah.yml@v1
    with:
      image_name: "ghcr.io/gc69720/social-backend"
      context: "."
      containerfile: "infra/podman/Containerfile.backend"
      tags: |
        ci-${{ github.run_number }}
        ${{ github.sha }}

  sbom-sign:
    needs: [build-image]
    uses: GC69720/social_ci-cd/.github/workflows/oci-sbom-sign.yml@v1
    with:
      image: "ghcr.io/gc69720/social-backend:${{ github.sha }}"
      generate_spdx: true
      sign_image: true
