name: app-ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-django:
    uses: GC69720/social_ci-cd/.github/workflows/python-django.yml@v1.1
    with:
      python_version: "3.12"
      working_directory: backend
      run_tests: true             # pytest renvoie 0 ou 5 (aucun test); les deux sont gérés côté workflow
      upload_test_artifacts: true
      django_settings_module: "backend.settings"
      requirements_file: "backend/requirements.txt"
      extra_install_cmd: ""
      enable_codeql: false
      docker_image_name: "gc69720/social-backend"
      docker_context: "backend"
      dockerfile: "backend/Dockerfile"
      docker_build_args: ""
    secrets:
      CLOUD_ROLE: ${{ secrets.CLOUD_ROLE }}