---
name: ci

'on':
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  # 1) Lint/Tests/CodeQL (comme avant, sans build d'image intégré)
  app-ci:
    uses: GC69720/social_ci-cd/.github/workflows/python-django.yml@v1
    with:
      python_version: "3.12"
      working_directory: "."
      run_tests: true
      upload_test_artifacts: false
      django_settings_module: ""   # ex: app.settings plus tard
      enable_codeql: true          # SAST activé
      docker_image_name: ""        # <- vide = pas de build via Docker action

  # 2) Build & Push OCI via Podman/Buildah (réutilisable)
  build-image:
    needs: [app-ci]
    uses: GC69720/social_ci-cd/.github/workflows/container-buildah.yml@v1
    with:
      image_name: "ghcr.io/gc69720/social-backend"
      context: "."
      containerfile: "infra/podman/Containerfile.backend"
      tags: |
        ci-${{ github.run_number }}
        ${{ github.sha }}
