---
name: ci

'on':
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# Autorisations pour le workflow appelé
permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  app-ci:
    uses: GC69720/social_ci-cd/.github/workflows/python-django.yml@v1.0.0
    with:
      python_version: "3.12"
      working_directory: "."          # mets "backend" quand ton Django existera
      run_tests: true                 # OK si on a un test de fumée
      upload_test_artifacts: false
      django_settings_module: ""      # ex. "app.settings" plus tard
      enable_codeql: false            # on activera plus tard
      docker_image_name: ""           # on activera plus tard
