---
name: secrets

'on':
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  gitleaks:
    uses: GC69720/social_ci-cd/.github/workflows/secret-scan.yml@v1
