
name: security

'on':
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write
  packages: read

jobs:
  trivy:
    uses: GC69720/social_ci-cd/.github/workflows/container-security.yml@v1.0.0
    with:
      image: ""   # ex. ghcr.io/gc69720/social-backend:ci-123 plus tard
      path: "."
