name: secrets
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  secret-scan:
    uses: GC69720/social_ci-cd/.github/workflows/secret-scan.yml@v1
    secrets: inherit
