---
name: security

'on':
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write
  packages: read

jobs:
  trivy:
    needs: [build-image]   # si tu veux t'assurer que l'image existe avant
    uses: GC69720/social_ci-cd/.github/workflows/container-security.yml@v1
    with:
      image: "ghcr.io/gc69720/social-backend:ci-${{ github.run_number }}"
      path: "."
